stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - npm install
    - echo "Building the project..."
    - npm run build
  only:
    - master

test_job:
  stage: test
  script:
    - npm test
    - echo "Running tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - scp ./build/* user@production-server:/var/www/html
  only:
    - master
