apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-new-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-new
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
