name: Good CI/CD Workflow with Python

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Установка зависимостей
      - name: Install dependencies
        run: pip install -r lab4/requirements.txt

      # Сборка проекта (замените на подходящую команду для вашего проекта)
      - name: Build the project
        run: echo "Pretend to build project"

      # Сохранение артефактов сборки
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Установка зависимостей
      - name: Install dependencies
        run: pip install -r lab4/requirements.txt

      # Загрузка артефактов сборки
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Запуск тестов
      - name: Run tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Загрузка артефактов сборки
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Деплой (замените DEPLOY_SERVER на реальный адрес сервера)
      - name: Deploy to production
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        run: |
          echo "Deploying to production..."
          scp build/* user@$DEPLOY_SERVER:/var/www/html
